version: '3.8'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
    - DB_HOST=database
    - DB_USER=root
    - DB_PASS=root
    - DB_NAME=testdb
    - DB_PORT=3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: ["bash","-c", "commandOne.sh"]

  database:
    build:
      context: ./data/mysql/
      dockerfile: Dockerfile
    container_name: database
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - DB_HOST=database
    - DB_USER=root
    - DB_PASS=root
    - DB_NAME=testdb
    - DB_PORT=3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
